lib/liquid_voting/delegations.ex
lib/liquid_voting/voting.ex
lib/liquid_voting/voting_results.ex
lib/liquid_voting/voting_weight.ex
lib/liquid_voting_web.ex
lib/liquid_voting_web/channels/user_socket.ex
lib/liquid_voting_web/resolvers/delegations.ex
lib/liquid_voting_web/resolvers/voting.ex
lib/liquid_voting_web/resolvers/voting_results.ex
lib/liquid_voting_web/views/error_view.ex
test/liquid_voting/delegations_test.exs
test/liquid_voting/voting_weight_test.exs

Closes #59.
Changes I included: 
- use `def func(), do:` syntax for one-line functions
- remove single pipes
- start pipes with raw value and not a function call 
- use pipes instead of reassignment where possible
- use `__MODULE__` where possible
- consolidate aliases under same namespace with `Mod.{ModA, ModB}`
Changes I didn't include (i.e. larger refactoring opportunities).
- doctests, see #63 
- nested control flow (making logic hard to follow) 
- large functions should be broken up into smaller ones doing only one thing
- pattern matching in function heads should be mainly used for control flow 
- module imports spacing, I've left this mostly as is, as it's mostly down to personal preference

Style refactors

---

lib/liquid_voting/voting/participant.ex
priv/repo/migrations/20200706113113_add_participant_uuid_to_participants.exs
test/liquid_voting/participants_test.exs

Notes:
Participant changeset doesn't validate uuid as "required field", since we want the uuid to be generated on creation of a participant. Thus, if the uuid is deleted by subsequent changes, that would not be caught. I wonder if this means we should have 2 changesets (one for create, another for update/edit - the latter having uuid as required field).
I have not set the uuid as index, nor unique_index. Currently we have a unique_index of:
```elixir
create unique_index(:participants, [:organization_uuid, :email],  name: :uniq_index_organization_uuid_participant_email)
```
I have also not set the uuid as primary key (currently is set to `id: "participants_pkey" PRIMARY KEY, btree (id) ...`)

api#14-add-uuid-column-to-participants-table

---

README.md
lib/liquid_voting_web/router.ex

This addresses issue [#84](https://github.com/liquidvotingio/api/issues/84): 'Graphql subscription not updating' 
Subscriptions will work when the interface is set to `:advanced` in 'router.ex'. It also seems that the graphiQL app doesn't work with subscriptions (no websocket set, even in advanced mode - though maybe this is configurable somehow?), but they work fine in the graphiQL browser window view. I have also edited the readme to include instructions to use the browser, where needed.

fix graphiql subscription with interface: :advanced in router.ex

---

.github/workflows/on_push.yml

To fix the `Unable to use a TTY - input is not a terminal or the right kind of file` warning on some builds like https://github.com/liquidvotingio/api/runs/976951705?check_suite_focus=true (see Deploy to GKE > Deploy step)
https://stackoverflow.com/questions/60826194/kubectl-exec-fails-with-the-error-unable-to-use-a-tty-input-is-not-a-terminal

Remove TTY option from deployment

---

lib/liquid_voting/delegations.ex
lib/liquid_voting/delegations/delegation.ex
priv/repo/migrations/20200817123412_add_delegations_global_boolean.exs
test/liquid_voting/delegations_test.exs

Closes [#110](https://github.com/liquidvotingio/api/issues/110)  
I have not exposed the `global` boolean to the absinthe layer as I was not sure if we want to do this, and it also seems beyond the scope of this issue. If we do expose this field to the absinthe layer, then we could list delegations by `global == true` or `global == false` via GraphQL queries, for example. Thoughts?

Add and set global boolean for delegations

---

test/liquid_voting/delegations_test.exs

closes [#115](https://github.com/liquidvotingio/api/issues/115)
I added 3 tests:
1. `create_delegation/1 with duplicate proposal-specific data returns error changeset`  
2. `create_delegation/1 with proposal-specifc data returns error if global delegation for same delegator/delegate pair exists`
3. `create_delegation/1 with global delegation data returns error if proposal-specific delegation for same delegator/delegate pair exists`

Add tests of double delegations scenarios

---

lib/liquid_voting/delegations.ex
lib/liquid_voting/delegations/delegation.ex
test/liquid_voting/delegations_test.exs
test/liquid_voting_web/absinthe/mutations/create_delegation_test.exs

closes [#45](https://github.com/liquidvotingio/api/issues/45)  
Q: Do we want the changeset error to apply to both fields (`delegator_id` & `delegate_id`)? I have only applied it to `delegate_id` (arbitrary choice).  
Q: Do we want a different error wording? I have suggested `delegate_id: ["delegator and delegate must be different"]`

Validate delegator and delegate are different

---

lib/liquid_voting_web/resolvers/delegations.ex
test/liquid_voting/delegations_test.exs
test/liquid_voting_web/absinthe/mutations/create_delegation_test.exs

closes #118  
**TLDR**: This 'fixes' the problem, but I don't particularly like the fix, and it perhaps raises more questions than it answers. This PR aims to stimulate discussion on the topic.  
**The issue:**  
createDelegation mutation with only 1 email field provided, misleadingly leads to an error of: `Could not create delegation ... %{delegate_id: ["can't be blank"], delegator_id: ["can't be blank"]}` This error does not help the user identify the missing email field.  
**The workaround:**     
Detect such a missing field (and the presence of one email field), and add the complimentary email field with a value of nil. Now a missing `:delegator_email` returns an error of `Could not create delegate ... email: ["can't be blank"]`, which is more useful.  
**Observations:**  
I have …

Correct error for missing delegate field

---

lib/liquid_voting/delegations.ex
test/liquid_voting/delegations_test.exs
test/liquid_voting_web/absinthe/mutations/delete_delegation_test.exs

I'm having a mental blank here. I have created a test, but I have used a graphQL mutation to create a delegation before I then delete it. Please see test/liquid_voting_web/absinthe/mutations/delete_delegation_test.exs   
I would like to insert the delegation without using a graphQL mutation, but can't think how to do it. The created mutation needs to be proposal specific and I need to be able to use the field values from the created delegation in the delete delegation mutation. How can I do this? Thanks!

Avoid incorrect delegation deletion

---

.github/workflows/on_pull_request.yml
.github/workflows/on_push.yml

Updates the deployment and smoke test jobs on pushes to use the Linode cluster.
It removes the intermediate gcloud auth step, and just passes Linode's kubeconfig in through a Github secret.
After merging all new deploys will be made to Linode and not to Google. So if the api.liquidvoting.io domain isn't resolving to the new IP yet, we won't be able to see the changes. So merging needs to be coordinated with domain migration (see https://github.com/liquidvotingio/deployment/issues/10)
Part of https://github.com/liquidvotingio/deployment/issues/35

Linode deploy

---

lib/liquid_voting/delegations.ex
test/liquid_voting/delegations_test.exs
test/liquid_voting_web/absinthe/mutations/create_delegation/existing_delegations_test.exs

See issue #125.
* 2 * failing tests (1 for each case). Test assertions will be more specific when changes fully implemented.  
* Current plan is something like this pseudo-code to modify upsert_delegation/1:  
```
#
#
```

Resolve conflicts for delegations with same participants

---

lib/liquid_voting/delegations.ex

Reading through https://elixirschool.com/blog/ecto-multi/, it's clear that what `Multi.run` does is run _operations_, so naming them after the operations themselves is clearer than naming after resources.
Tweaked some variable namings as well.
(PR doesn't need to be squashed, commits are good to be merged as they are)

Refactor multis

---

lib/liquid_voting/delegations.ex
test/liquid_voting/delegations_test.exs
test/liquid_voting_web/absinthe/mutations/create_delegation/existing_delegations_test.exs
test/liquid_voting_web/absinthe/mutations/create_delegation/with_emails/existing_delegations_test.exs
test/liquid_voting_web/absinthe/mutations/create_delegation/with_ids/existing_delegations_test.exs

Create delegation with ids uses all validations

---

test/liquid_voting_web/absinthe/mutations/delete_delegation_test.exs

Just some test cleanup I noticed could be done after merging https://github.com/liquidvotingio/api/pull/152
Removes extra request in one test and simplifies payload on setup request for another one.

Simplify absinthe delegation deletion test

---

.github/workflows/on_pull_request.yml
.github/workflows/on_push.yml
Dockerfile

The [build is breaking on the latest dependabot PR merges](https://github.com/liquidvotingio/api/runs/1736752739?check_suite_focus=true), and it turns out that updating the elixir images on the Dockerfile fixes that. This PR then updates it there and on the CI steps

Update elixir images on Dockerfile and CI

---

lib/liquid_voting/voting.ex
lib/liquid_voting_web/resolvers/voting.ex

No great breakthough, but let's keep this for now, as it
successfully sends related spans from core api action and
resolver action (list_votes/1 / votes/3).
Also reports related variable value (organization_id). We may not need
this, but demonstrates we can do this kind of thing.

Add opentelemetry

---

lib/liquid_voting/voting.ex
lib/liquid_voting_web/resolvers/voting.ex

Currently we are only creating traces on Honeycomb for the
list_votes/1 def and the related resolver votes/3 def (and
only for one form of the latter).

Add Phoenix :request_id to our test traces.

---

lib/liquid_voting/voting.ex
lib/liquid_voting/voting_results.ex
lib/liquid_voting_web/resolvers/voting.ex

Includes trace attribute field of 'result' for displaying details of `:ok` or `:error` result, where applicable.
Includes all functions involved in successful create vote path, initiated via GraphQl `createVote` mutation, and specific failure paths (but not all, yet).

Include success or failure paths in traces.

---

test/liquid_voting/delegations_test.exs

I noticed a number of 'unused var' warnings for this test file, so I removed the unused vars.

Remove unused vars in delegations_test.ex.

---

lib/liquid_voting/voting.ex
test/liquid_voting_web/absinthe/mutations/create_delegation/before_creating_related_votes_test.exs

This fixes case where a voter is already the _delegator_ in a delegation for the same proposal (`proposal_url` + `voting_method`).
Prior to this fix, the process of searching for, and deleting the related delegation, in `create_vote/1` in `voting.ex`, returned a vote without the associated `voting_method` being preloaded, which would cause a `createVote` mutation to fail due to the associated `voting_method` being unavailable.
Adds a preload of `voting_method` when the vote is returned in this case.
Also adds a test of the case that highlighted this bug + a similar test of creating a vote for the _delegate_, following a proposal-delegation creation.

Bugfix: Preload voting_method when create vote for delegator.
